In [4]:
import numpy as np
import pandas as pd 

root_seed = 100

np.random.seed(root_seed)

seeds = np.random.randint(0,256,size=(20,4))

seed_table = pd.DataFrame(seeds,columns=['Dataset Split','Dataset Transform','Dataset Shuffle','Model Weights'])
seed_table.index = list(range(1,21))
seed_table.index.name = 'TrialNumber'
seed_table

             Dataset Split  Dataset Transform  Dataset Shuffle  Model Weights
TrialNumber
1                        8                 24               67            103
2                       87                 79              176            138
3                       94                180               98             53
4                       66                226               14             34
5                      241                240               24            143
6                      228                107               60             58
7                      144                251              137             93
8                       86                130              155            108
9                      132                159              129            141
10                     245                211              100              4
11                      91                187               67            135
12                      49                175              193             61
13                      14                183              199            251
14                      80                  2              121            105
15                     222                147              226             63
16                     181                 27               56            238
17                     113                158              176             47
18                     167                109               38            172
19                      18                192              184            162
20                     181                202               17             72